ALTER TABLE USERS
ADD COLUMN  FirstName 		VARCHAR(100) NOT NULL,
ADD COLUMN  LastName 		VARCHAR(100) NOT NULL,
ADD COLUMN  CourseEdition 	VARCHAR(100) NOT NULL,
ADD COLUMN	UserGrade		INT NOT NULL DEFAULT 1;

ALTER TABLE REF_LIBRARY
ADD COLUMN RefID INT NULL,
ADD COLUMN CourseEdition VARCHAR(100) NOT NULL,
ADD COLUMN Category VARCHAR(100) NULL; 

CREATE TABLE USER_ROLES
(
	UserRoleID INT NOT NULL PRIMARY KEY,
    UserRoleLabel VARCHAR(100) NOT NULL
);

INSERT INTO USER_ROLES VALUES (1, 'User'), (2, 'Moderator'), (3, 'Admin');

CREATE TABLE COURSE_EDITION
(
	CourseEditonID INT NOT NULL PRIMARY KEY
);

INSERT INTO COURSE_EDITION VALUES (15), (16), (17);

ALTER TABLE REF_LIBRARY
ADD FULLTEXT(Title, Keywords);