ALTER TABLE REF_LIBRARY 
	ADD COLUMN Link VARCHAR(2500) NULL

ALTER TABLE OWNED_REFS
	DROP COLUMN Duration,
    	ADD COLUMN Deadline DATE NOT NULL
    
ALTER TABLE EXPORTED_REFS 
	ADD COLUMN MAX_EXPORTS INT NOT NULL;
